version: '3.1'

services:
  # postgres:
  #   image: postgres
  #   restart: always
  #   environment:
  #     POSTGRES_PASSWORD: 123
  #     POSTGRES_USERNAME: postgres
  #   ports:
  #     - 5432:5432

  redis:
    image: redis:alpine
    restart: always
    ports:
      - '6379:6379'

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
