"""migration

Revision ID: 16952c6082e2
Revises: 
Create Date: 2024-01-09 21:30:56.467563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16952c6082e2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('member',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=255), nullable=True),
    sa.Column('birthday', sa.String(length=255), nullable=True, comment='Birthday'),
    sa.Column('name', sa.String(length=255), nullable=True, comment='Full name or name'),
    sa.Column('refresh_token', sa.String(length=255), nullable=True),
    sa.Column('role_id', sa.SmallInteger(), nullable=True, comment='Role id member'),
    sa.Column('gender', sa.SmallInteger(), nullable=True),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.SmallInteger(), nullable=False, comment='INACTIVE = 0, ACTIVE = 1, PENDING = 2'),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_member_birthday'), 'member', ['birthday'], unique=False)
    op.create_index(op.f('ix_member_email'), 'member', ['email'], unique=True)
    op.create_index(op.f('ix_member_gender'), 'member', ['gender'], unique=False)
    op.create_index(op.f('ix_member_id'), 'member', ['id'], unique=False)
    op.create_index(op.f('ix_member_name'), 'member', ['name'], unique=False)
    op.create_index(op.f('ix_member_phone'), 'member', ['phone'], unique=True)
    op.create_index(op.f('ix_member_role_id'), 'member', ['role_id'], unique=False)
    op.create_index(op.f('ix_member_username'), 'member', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_member_username'), table_name='member')
    op.drop_index(op.f('ix_member_role_id'), table_name='member')
    op.drop_index(op.f('ix_member_phone'), table_name='member')
    op.drop_index(op.f('ix_member_name'), table_name='member')
    op.drop_index(op.f('ix_member_id'), table_name='member')
    op.drop_index(op.f('ix_member_gender'), table_name='member')
    op.drop_index(op.f('ix_member_email'), table_name='member')
    op.drop_index(op.f('ix_member_birthday'), table_name='member')
    op.drop_table('member')
    # ### end Alembic commands ###
