"""migration

Revision ID: 28080db712e0
Revises: 
Create Date: 2024-01-10 10:51:26.686440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '28080db712e0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('member',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('password', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('birthday', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('refresh_token', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('gender', sa.Integer(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_member_birthday'), 'member', ['birthday'], unique=False)
    op.create_index(op.f('ix_member_email'), 'member', ['email'], unique=True)
    op.create_index(op.f('ix_member_gender'), 'member', ['gender'], unique=False)
    op.create_index(op.f('ix_member_name'), 'member', ['name'], unique=False)
    op.create_index(op.f('ix_member_phone'), 'member', ['phone'], unique=True)
    op.create_index(op.f('ix_member_role_id'), 'member', ['role_id'], unique=False)
    op.create_index(op.f('ix_member_status'), 'member', ['status'], unique=False)
    op.create_index(op.f('ix_member_username'), 'member', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_member_username'), table_name='member')
    op.drop_index(op.f('ix_member_status'), table_name='member')
    op.drop_index(op.f('ix_member_role_id'), table_name='member')
    op.drop_index(op.f('ix_member_phone'), table_name='member')
    op.drop_index(op.f('ix_member_name'), table_name='member')
    op.drop_index(op.f('ix_member_gender'), table_name='member')
    op.drop_index(op.f('ix_member_email'), table_name='member')
    op.drop_index(op.f('ix_member_birthday'), table_name='member')
    op.drop_table('member')
    # ### end Alembic commands ###
